### ISSUE TITLE
(RP204-) getCodeFromTimeStamp() returns incorrect code

### ISSUE THREAD

**Issue by Devnol** [weravech/TOTP-MCU#2]
MCU: RP2040
Compiler: arm-none-eabi-gcc
Compiler host machine: macOS

I have converted the base32 string provided by the 2fa server to hex using the Base32 (RFC 3548, RFC 4648) algorithm and provided it as hmacKey[] to the TOTP constructor.

I have also set the timezone to UTC+3 since it's summer and I'm in Greece using setTimezone(3), but the unix timestamp provided by the RP2040 RTC is already corrected to UTC±0. Is that how I'm supposed to do it?

Anyway, the provided timestamp from the RTC is correct but the generated token is invalid.
Any ideas?

**Comment by Netthaw** [comment]
If timestamp on both side (2FA Server and RP2040) are based from UTC±0. It no need to use setTimezone.
```
TOTP(hmacKey, 10, 30);                                     // Secret key, Key length, Timestep (30s)

// setTimezone(0);                                         // Set timezone UTC
uint32_t newCode = getCodeFromTimestamp(1557414000);       // Timestamp Now
```

**Comment by Devnol** [comment]
Oh ok so that basically does correction if the user hasn't done so beforehand. Thanks a lot I'll try it when I get home. Also you should probably make that a bit clearer in the README, as well as the fact that the string provided by most apps is base32 and needs to be upcased and decoded, because I initially thought it was ascii and converted it like that which obviously didn't work.
Btw congrats and thanks a lot for helping out even 2 years after this library was completed!

**Comment by Netthaw** [comment]
Thank you very much for your comment. I will update Readme clearly!!

**Comment by AkshaySQT** [comment]
hh
