### ISSUE TITLE
OTP matching

### ISSUE THREAD

**Issue by rakshi-1988** [weravech/TOTP-MCU#8]
I am using the library on atmega controller and the otp generated on my controller is not matching with the code generated online, I am using same Secret key on both online simulator and on my MCU.
I am using https://www.nayuki.io/page/time-based-one-time-password-tools
link to check the OTP where we can pass the time code manually also.
Can you confirm whether this library is supported as per the link which also says it is developed as per RFC 6238

**Comment by Netthaw** [comment]
Hi. As i tested, It works fine for me.
https://www.nayuki.io/page/time-based-one-time-password-tools
- Secret key: JV4UYZLHN5CG633S // Convert text "MyLegoDoor" to base32 
- Code length: 6
- Timestamp: Uncheck "Current time" and input 1557414000

Tested with my example in Readme
