### ISSUE TITLE
Not compiling properly, and get wrong code in the end

### ISSUE THREAD

**Issue by shideneyu** [weravech/TOTP-MCU#9]
I am trying to use your library to use with my Flipper Zero. I almost don't know C, I spent 7 hours straight trying to figure out how to use your library and ended up understanding most of the code now. However the one time password I generate is always wrong.
Here is my issue: I try to generate the code `191565`, coming from the upcased BASE32 seed `MYLEGODOOR`.

https://www.nayuki.io/page/time-based-one-time-password-tools

![image](https://user-images.githubusercontent.com/876824/180639008-a80acb29-1fe0-43d7-ac4b-93c18eaa508e.png)

So here is my code:

```c
#include <stdio.h>
#include <TOTP.h>

int
main (void)
{
  uint8_t _hmacKey[] = {0x4d, 0x59, 0x4c, 0x45, 0x47, 0x4f, 0x44, 0x4f, 0x4f, 0x52};
  TOTP(_hmacKey, 10, 30);           
  uint32_t newCode = getCodeFromTimestamp(1557414000);
  printf(" %u \n", newCode);
  return 0;
}
```

The hmackey is correct. We can test it here: https://cryptii.com/pipes/base32-to-hex

![image](https://user-images.githubusercontent.com/876824/180639389-b626f077-33b3-425c-8a29-2050b8709618.png)

To get it compiled, I cloned your project and ran `gcc -I .  main.c -o main -lm TOTP.c sha1.c`

Then I get this error:

```
/usr/bin/ld: /tmp/ccfIQ8hj.o:(.bss+0x0): multiple definition of `buffer'; /tmp/ccqtE5YG.o:(.bss+0x0): first defined here
/usr/bin/ld: /tmp/ccfIQ8hj.o:(.bss+0x40): multiple definition of `state'; /tmp/ccqtE5YG.o:(.bss+0x40): first defined here
/usr/bin/ld: /tmp/ccfIQ8hj.o:(.bss+0x54): multiple definition of `bufferOffset'; /tmp/ccqtE5YG.o:(.bss+0x54): first defined here
/usr/bin/ld: /tmp/ccfIQ8hj.o:(.bss+0x58): multiple definition of `byteCount'; /tmp/ccqtE5YG.o:(.bss+0x58): first defined here
/usr/bin/ld: /tmp/ccfIQ8hj.o:(.bss+0x60): multiple definition of `keyBuffer'; /tmp/ccqtE5YG.o:(.bss+0x60): first defined here
/usr/bin/ld: /tmp/ccfIQ8hj.o:(.bss+0xa0): multiple definition of `innerHash'; /tmp/ccqtE5YG.o:(.bss+0xa0): first defined here
```

This is the exact same error when I try to push it to my Flipper Zero. To fix it, I followed @[Astrrra](https://github.com/Astrrra)
procedure here :  https://github.com/wetox-team/flipperzero-firmware/blob/gen-totp/lib/TOTP-MCU/sha1.h

By moving a few lines from the `sha1.h` header to the `sha1.c` file on the top.

Those lines:

```c
union _buffer {
  uint8_t b[BLOCK_LENGTH];
  uint32_t w[BLOCK_LENGTH/4];
} buffer;
union _state {
  uint8_t b[HASH_LENGTH];
  uint32_t w[HASH_LENGTH/4];
} state;

uint8_t bufferOffset;
uint32_t byteCount;
uint8_t keyBuffer[BLOCK_LENGTH];
uint8_t innerHash[HASH_LENGTH];
```

Once it's done, I can finaly compile it.

However the code I get is `364961`, not `191565`

I am out of ideas on how to make it work. I understand that moving those lines is actually corrupting the behaviour of the engine. Do you know how to fix the compilation ? Thank you very much for your help it's greatly appreciated :pray:

**Comment by Netthaw** [comment]
Hi @shideneyu 

According https://www.nayuki.io/page/time-based-one-time-password-tools
The input must be base32, You need to convert string input first https://emn178.github.io/online-tools/base32_encode.html

In this case, 
String is MYLEGODOOR. 
After converted into Base32 is JVMUYRKHJ5CE6T2S

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1386844/180640506-d6d7bde5-6c9f-4e7f-9aa5-b18d574285f1.png">

The result will be 364961 :)

**Comment by shideneyu** [comment]
Wow, it works !!! I wonder how didn't see this earlier ! Thank you so much !
